# Generated by Django 4.1.7 on 2023-02-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coreapp", "0002_teamscore"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teamscore",
            old_name="team_name",
            new_name="team_name_1",
        ),
        migrations.RemoveField(
            model_name="teamscore",
            name="team_score",
        ),
        migrations.AddField(
            model_name="teamscore",
            name="team_name_2",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="teamscore",
            name="team_score_1",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamscore",
            name="team_score_2",
            field=models.IntegerField(default=0),
        ),
    ]
