# Generated by Django 4.1.7 on 2023-02-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coreapp", "0003_rename_team_name_teamscore_team_name_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamscore",
            name="user",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
