# Generated by Django 4.1.7 on 2023-02-15 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coreapp", "0004_alter_teamscore_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamscore",
            name="file",
        ),
    ]
