# Generated by Django 4.1.7 on 2023-02-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coreapp", "0008_teamscore_file_teamscore_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamscore",
            name="file",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="teamscore",
            name="user",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
