# Generated by Django 4.1.7 on 2023-02-15 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("coreapp", "0009_alter_teamscore_file_alter_teamscore_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamscore",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="coreapp.files",
            ),
        ),
        migrations.AlterField(
            model_name="teamscore",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
