# Generated by Django 4.1.7 on 2023-02-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coreapp", "0012_alter_files_file_uploaded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamscore",
            name="team_name_1",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="teamscore",
            name="team_name_2",
            field=models.CharField(max_length=100),
        ),
    ]
